services:
  - type: web
    name: helloworld-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_ACCESS_TOKEN_EXPIRATION
        value: "900000"
      - key: JWT_REFRESH_TOKEN_EXPIRATION
        value: "604800000"
      - key: CORS_ALLOWED_ORIGINS
        sync: false
